apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.KubeStateMetricsName }}
  name: {{ .Values.KubeStateMetricsName }}
  namespace:  {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.KubeStateMetricsName }}
  template:
    metadata:
      labels:
        app: {{ .Values.KubeStateMetricsName }}
    spec:
      serviceAccountName: {{ .Values.KubeStateMetricsName }}
      containers:
      - name: {{ .Values.KubeStateMetricsName }}
        image:   {{ .Values.image.repository }}:{{ .Values.image.tag }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
