apiVersion: v1
kind: Service
metadata:
  namespace: crane-monitoring
  name: grafana-bak
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana-bak
  selector:
    app: grafana-bak
  sessionAffinity: None
  type: LoadBalancer