apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.CostExporterName }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.CostExporterName }}
rules:
  - apiGroups: [ '*' ]
    resources: [ '*' ]
    verbs: [ "*" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.CostExporterName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.CostExporterName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.CostExporterName }}
  apiGroup: rbac.authorization.k8s.io
