apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ .Values.NodeExporterName }}
  name: {{ .Values.NodeExporterName }}
  namespace:  {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.NodeExporterName }}
  template:
    metadata:
      labels:
        app: {{ .Values.NodeExporterName }}
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - name: {{ .Values.NodeExporterName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - --web.listen-address=$(HOSTIP):9100
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
            - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
          ports:
            - containerPort: 9100
          env:
            - name: HOSTIP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
          volumeMounts:
            - name: proc
              mountPath: /host/proc
            - name: sys
              mountPath: /host/sys
            - name: root
              mountPath: /host/root
              mountPropagation: HostToContainer
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}